#arm:

  #similar to https://github.com/IFL-CAMP/iiwa_stack/blob/master/iiwa_control/config/iiwa_control.yaml ------

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  # Controllers for singular joint ------------------------------------

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J0_controller:
    type: position_controllers/JointPositionController
    joint: j0
  
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: j1
  
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: j2
  
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: j3